service: bokningsapi
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  addBooking:
    handler: functions/addBooking/index.handler
    events:
      - httpApi:
          path: '/add'
          method: POST
  changeBooking:
    handler: functions/changeBooking/index.handler
    events:
      - httpApi:
          path: '/change'
          method: PATCH
  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: '/delete'
          method: DELETE
  getBookings:
    handler: functions/getBookings/index.handler
    events:
      - httpApi:
          path: '/get'
          method: GET
  addRooms:
    handler: functions/addRooms/index.handler
    events:
      - httpApi:
          path: '/addRooms'
          method: POST

resources:
  Resources:
    teamDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: booking-db # Database table name
        AttributeDefinitions:
          - AttributeName: id # database item id
            AttributeType: S # String
        KeySchema:
          - AttributeName: id # database key id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    roomDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: room-db
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: S
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
